checking
olgadanilowa/petsshop pull request #2
Opened 2023-09-25 10:23 UTC by olgadanilowa

2023-09-26 13:12 UTC, alinashabalina requested changes

2023-09-26 13:12 UTC, alinashabalina commented on tests/test_post_create_user.py
> +    #print(create_test_users_body)
надо будет сегодня подтереть все принты

2023-09-26 13:12 UTC, alinashabalina commented on tests/test_post_create_user.py
> +    print (response)
и вот тут вот тоже

2023-09-26 13:12 UTC, alinashabalina commented on tests/test_post_create_user.py
> +    print(user_data)
и тут

2023-09-26 13:12 UTC, alinashabalina commented on tests/test_post_create_user.py
> +    print(user_data)
+ имхо записывать а-ля user_data = response.json() - это лишнее, лишняя строчка, которая в принципе к читабельности дальнейшего кода добавит 1%

можно просто дальше везде писать типа response.json()['result']['id'] == чему-то там

2023-09-28 18:30 UTC, closed without merging

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented
+

2023-09-28 18:30 UTC, olgadanilowa commented on tests/test_post_create_user.py
> +    print(user_data)
+